### ISSUE TITLE
loadPath() has no option to use Max Velocity, Acceleration or Direction from the JSON file.

### ISSUE THREAD

**Issue by WarrenReynolds** [mjansen4857/pathplannerlib#5]
I found this issue in the pathplanner repo 
[linked here](https://github.com/mjansen4857/pathplanner/issues/70)
but I feel this should be located in this repo instead.

Summary of the issue. 
The c++ .loadPath() method has no option of using the values inside the Json file for Max Velocity, Max Acceleration, and Path Reversed.  Currently these have to be hard coded and supplied as parameters to loadPath() method which sort of defeats the purpose of having the ability to modify paths without needing to recompile code.

A backward compatible solution could be to change the implementation of the existing loadPath method to include a optional 5th parameter as bool UseJsonValuesForVelAccDirection=false.

Then add a single parameter constructor in the .h file that only takes a filename, that calls the 5 parameter method with UseJsonValuesForVelAccDirection=true, with fake values for Vel, Acc, Reversed as they will be ignored.

Then modify the .cpp to load use the json values for Max Vel, Max Acc and Direct instead of using the parsed values if it detects UseJsonValuesForVelAccDirection==true

Maybe need to parse the json file twice as this info is below the waypoints.  Not sure if this is an issue, unfortunately I don't know enough about JSON processing.

**Comment by mjansen4857** [comment]
I want to keep all PathPlanner and PathPlannerLib related issues in the main repository since it has more visibility. People will look at the main repo for issues before they find this one. And a lot of PathPlannerLib changes will also need GUI app changes as well so it makes more sense to me to leave all issues in the main repo. I'll add my input in the main repo's issue.
